---

- stat: path={{selenium_jar_dir}}
  register: sd

- stat: path="{{selenium_jar_dir}}/selenium-server-standalone.jar"
  register: sf


- debug: msg="{{sd}}"

- name: create selenium base dir
  file: path={{selenium_jar_dir}} owner=root group=root mode=755 state=directory
  when: sd.stat.exists == False

- name: download selenium
  get_url: url=http://selenium-release.storage.googleapis.com/{{selenium_version_major_minor}}/selenium-server-standalone-{{selenium_version_major_minor_bug}}.jar dest={{selenium_jar_dir}}/selenium-server-standalone-{{selenium_version_major_minor_bug}}.jar

- name: symlink selenium
  file: src={{selenium_jar_dir}}/selenium-server-standalone-{{selenium_version_major_minor_bug}}.jar dest=/opt/selenium/selenium-server-standalone.jar state=link
